---
name: pre-commit

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: no-commit-to-branch
      - uses: fish-actions/install-fish@v1.1.0
      - run: pre-commit try-repo . fish_syntax --verbose --all-files
      - run: pre-commit try-repo . fish_indent --verbose --all-files
